name: ci.yml
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-and-analyze:
    name: Build, Test & SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/Directory.Packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Add dotnet tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore tools
        run: dotnet tool restore

      - name: Begin SonarQube Analysis
        run: |
          dotnet sonarscanner begin \
            /k:"atomify-backend" \
            /o:"samuelzedec" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.vscoveragexml.reportsPaths="coverage.xml" \
            /d:sonar.exclusions="**/Migrations/**,**/bin/**,**/obj/**,**/appsettings*.json,**/Dockerfile*,**/Seeders/**,**/*.html,**/Mappings/**" \
            /d:sonar.coverage.exclusions="**/Persistence/**,**/ValidationBehavior.cs,**/Program.cs,**/*Validator.cs,**/Extensions/**,**/Repositories/**,**/Options/**,**/Constants/**,**/Dtos/**,**/Events/**,**/Exceptions/**,**/Abstractions/**,**/DependencyInjection.cs,**/Setups/**,**/Results/**"

      - name: Restore packages
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-incremental --no-restore

      - name: Test with Coverage
        run: |
          dotnet-coverage collect \
            "dotnet test -c Release --no-build --no-restore" \
            -f xml \
            -o coverage.xml

      - name: End SonarQube Analysis
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"